Feature/add revmon collaboration banner
planetarium/NineChronicles pull request #1273
Opened 2022-03-22 03:51 UTC by boscohyun

### Related Links

https://app.asana.com/0/958521740385861/1201996079589665/f

### Screenshot

<img width="296" alt="image" src="https://user-images.githubusercontent.com/6128868/159403994-d669d858-f3d7-4877-9d09-d3d673066dfd.png">

<img width="433" alt="image" src="https://user-images.githubusercontent.com/6128868/159404507-558f4703-f7ee-4d48-ba31-33b9c44c3e7a.png">

<img width="163" alt="image" src="https://user-images.githubusercontent.com/6128868/159403971-d76c932e-a1bd-4bc6-a2c3-00b7ab95e7a9.png">

2022-03-22 04:27 UTC, sonohoshi commented on nekoyume/Assets/_Scripts/Extension/DateTimeExtensions.cs
> +                DateTime.ParseExact(begin, "yyyy-MM-ddTHH:mm:ss", null),
The dateTime format of the comment and the dateTime format of the code appear to be different. Is it okay?
comment : `"yyyy-MM-ddTHH-mm-ss"`
code : `"yyyy-MM-ddTHH:mm:ss"`

2022-03-22 04:27 UTC, hskim881028 requested changes

2022-03-22 04:27 UTC, hskim881028 commented on nekoyume/Assets/_Scripts/UI/Widget/EventBanner.cs
> +                    childCount--;
Is it OK to change `childCount` during loop?

2022-03-24 09:20 UTC, hskim881028 commented on nekoyume/Assets/_Scripts/UI/Widget/EventBanner.cs
> +                    childCount--;
![화면 캡처 2022-03-24 181805](https://user-images.githubusercontent.com/40553495/159883968-b8d40522-7a7b-4618-b803-3b7e9de91d02.jpg)

2022-03-24 09:21 UTC, hskim881028 approved these changes

2022-03-24 09:35 UTC, merged