Improve character title
planetarium/NineChronicles pull request #170
Opened 2021-05-04 09:28 UTC by hskim881028

### Description

- Detach character title from the HP bar. Add HudContainer. Then load the HP bar and title into the container.
- Improve character title 
- Add Resource Helper. It manages scriptable objects.

### How to test

- Equip character title

### Related Links

- [Link](https://app.asana.com/0/958521740385861/1198932974018853/f)

### Required Reviewers

@planetarium/9c-dev , @Namyujeong 

### Screenshot

![image](https://user-images.githubusercontent.com/40553495/116984695-7dfbe000-ad06-11eb-932b-3d8c852213ae.png)

2021-05-04 09:52 UTC, boscohyun commented on nekoyume/Assets/_Scripts/Helper/ResourcesHelper.cs
> +    public static class ResourcesHelper
How about this initializing asynchronously like below.
```cs
// in Game.cs
await ResourceHelper.InitializeAsync();
or
yield return StartCoroutine(ResourceHelper.CoInitialize());
```

2021-05-04 10:18 UTC, Namyujeong requested changes
1. There's a weird title faintly above the character's head.
![image](https://user-images.githubusercontent.com/41294407/116989376-9e2e9d80-ad0c-11eb-815e-ee659e27abae.png)
2. In situations where there are several characters, a title is mounted on one character, and if you log on as a character without the title, the title effect that is being mounted on another character will appear.
![image](https://user-images.githubusercontent.com/41294407/116989814-375db400-ad0d-11eb-980c-06eff7e1d1ec.png)
![image](https://user-images.githubusercontent.com/41294407/116989540-d930d100-ad0c-11eb-8793-62487b3a766d.png)

2021-05-06 08:10 UTC, Namyujeong approved these changes
All problems have been solved!

![image](https://user-images.githubusercontent.com/41294407/117262420-33a46b80-ae8c-11eb-898f-072a61902026.png)

![image](https://user-images.githubusercontent.com/41294407/117262508-4c148600-ae8c-11eb-8368-e9982013bce1.png)

2021-05-06 09:16 UTC, boscohyun approved these changes

2021-05-06 09:16 UTC, boscohyun commented on nekoyume/Assets/_Scripts/Game/Game.cs
> +            // yield return StartCoroutine();
```suggestion
```

2021-05-12 05:20 UTC, merged