Update shop filter
planetarium/NineChronicles pull request #2590
Opened 2023-04-25 03:14 UTC by tyrosine1153

### Description

- Edit ShopState request 
  - add itemIds param to improve shop buy filter
  - edit ItemProducts caching dict to only list
- Add Shop Sort - EquipmentLevel, OptionCount, UnitPrice

### Related Links

[23.2Q 샵 개선 - 상점정렬, 필터 수정](https://app.asana.com/0/958521740385861/1204439171665346/f)

2023-04-25 06:45 UTC, hskim881028 requested changes

2023-04-25 06:45 UTC, hskim881028 commented on nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
> +        private int _loadingCount;
`_loadingCount` is used for what purpose?

2023-04-25 06:45 UTC, hskim881028 commented on nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
> +            if (offset == 0)
```suggestion
            if (reset)
```

2023-04-25 06:45 UTC, hskim881028 commented on nekoyume/Assets/_Scripts/State/ReactiveShopState.cs
> +            if (offset == 0)
```suggestion
            if (reset)
```

2023-04-25 06:45 UTC, hskim881028 commented on nekoyume/Assets/_Scripts/UI/Shop/BuyView.cs
> +                    filter, orderType, limit * 5, reset, filteredItemIds);
```suggestion
                    filter, orderType, limit * 15, reset, filteredItemIds);
```

2023-04-26 01:43 UTC, sonohoshi approved these changes

2023-04-26 01:46 UTC, hskim881028 approved these changes

2023-04-26 02:17 UTC, sonohoshi approved these changes

2023-04-26 02:21 UTC, merged