Feature/collection shortcut
planetarium/NineChronicles pull request #4428
Opened 2024-03-13 04:32 UTC by tyrosine1153

### Description

- https://github.com/planetarium/NineChronicles/issues/4330
- https://github.com/planetarium/NineChronicles/issues/4408

### Screenshot

...

2024-03-13 05:44 UTC, sonohoshi commented on nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
> +                repeatButton.gameObject.SetActive(canExit);
여기서 canExit가 이벤트 던전의 티켓 갯수 같은건 고려하지 않는 것 같은데 괜찮나요

2024-03-13 05:45 UTC, sonohoshi reviewed
ShortcutHelper 변경이 너무 커서 정확히 뭐가 바뀐건지 설명해주실 수 있나요? @tyrosine1153

2024-03-13 06:42 UTC, tyrosine1153 commented on nekoyume/Assets/_Scripts/UI/Widget/Popup/BattleResultPopup.cs
> +                repeatButton.gameObject.SetActive(canExit);
다른 pr로 들어갔어야 하는 변경점이 들어갔군요;; 이벤트 던전은 AP포션, 티켓같은 재화가 부족해도 다음 전투에서 구매해서 사용할 수 있도록 Repeat, Stage를 허용하는게 스펙입니다.

2024-03-14 08:01 UTC, ipdae commented
다른 pr과 총돌이 나는것같습니다. 그리고 타겟브랜치를 preapre/160.0.x로 돌려야할것같네요.

2024-03-14 08:05 UTC, eugene-doobu commented
Collection.cs의 충돌은 해당 브랜치의 작업을 선택해주시고 Show(bool)메서드 안에 있는 211라인의 UpdateScrollView() 메서드를 호출하는 부분을 UpdateItems()를 호출해주는것으로 변경하면 해결될 것으로 보입니다

2024-03-14 08:28 UTC, eugene-doobu requested changes

2024-03-14 08:28 UTC, eugene-doobu commented on nekoyume/Assets/_Scripts/UI/Widget/Collection.cs
>              UpdateScrollView();
Collection.cs의 충돌은 해당 브랜치의 작업을 선택해주시고 Show(bool)메서드 안에 있는 UpdateScrollView() 메서드를 호출하는 부분을 UpdateItems()를 호출해주는것으로 변경하면 해결될 것으로 보입니다 

```cs
        public override void Show(bool ignoreShowAnimation = false)
        {
            base.Show(ignoreShowAnimation);

            Find<HeaderMenuStatic>().UpdateAssets(HeaderMenuStatic.AssetVisibleState.Combination);

            var toggle = itemTypeToggles.First().toggle;
            toggle.isOn = !toggle.isOn;

            UpdateToggleView();
            UpdateStatToggleView();
            UpdateItems();
            
            CheckMobileShopCategoryCached();
        }

        private async void CheckMobileShopCategoryCached()
        {
#if UNITY_ANDROID || UNITY_IOS
            // For get AcquisitionPlace
            var mobileShop = Find<MobileShop>();
            if (mobileShop.CachedCategorySchemas == null)
            {
                await mobileShop.CacheCategorySchemas();
            }
#endif
        }
```

2024-03-14 10:50 UTC, sonohoshi approved these changes

2024-03-15 04:26 UTC, jonny-jeahyunchoi commented on nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
> +        public bool TryGetCategoryName(int itemId, out string categoryName)
사용하는곳이 없는 함수인것같은데 확인부탁드립니다~!

2024-03-15 04:27 UTC, jonny-jeahyunchoi commented on nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
> +        public IReadOnlyList<CategorySchema> CachedCategorySchemas { get; private set; }
이름을 가져오기위해서 사용하는용도라면 IAPStoreManager의 _initailizedProductSchema 를사용하는건 어떠한가요?

2024-03-15 05:22 UTC, eugene-doobu approved these changes

2024-03-15 06:15 UTC, tyrosine1153 commented on nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
> +        public bool TryGetCategoryName(int itemId, out string categoryName)
@jonny-jeahyunchoi  더스트, AP포션, 모래시계를 샵에서 판매중일 경우 카테고리로 이름을 가져오기 위해 만든 메서드입니다! ShortCutHelper.cs에서 지금 사용중이고, 받아온 카테고리 이름은 MobileShop의 ShowAsTab을 통해 바로가기를 했을 때 원하는 탭으로 들어가도록 하고 있습니다.

2024-03-15 06:20 UTC, tyrosine1153 commented on nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
> +        public IReadOnlyList<CategorySchema> CachedCategorySchemas { get; private set; }
위에서 설명드린 것과 같은 이유로 카테고리의 이름을 사용해야 하기 떄문에 CategorySchema가 필요하긴 합니다만,  _initailizedProductSchema의 자료형을 CategorySchema로 수정해서 사용하는게 나을까요?

2024-03-15 06:24 UTC, jonny-jeahyunchoi commented on nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
> +        public bool TryGetCategoryName(int itemId, out string categoryName)
오 확인했습니다~! 변경사항이커서 해당파일이 접혀있어서 확인을못했던거였네요~!

2024-03-15 06:26 UTC, jonny-jeahyunchoi commented on nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
> +        public IReadOnlyList<CategorySchema> CachedCategorySchemas { get; private set; }
음 다시확인해보니 프로덕트가아니라 카테고리가 필요해서 따로만드신거군요~!
카테고리 이름만사용해야된다고하면 _initailizedProductSchema 를 갱신하는시점에 따로 캐시해서 사용하는것이 불필요한 통신을 줄일수있을것같습니다~!

2024-03-15 08:20 UTC, jonny-jeahyunchoi approved these changes

2024-03-15 08:22 UTC, tyrosine1153 commented on nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
> +        public IReadOnlyList<CategorySchema> CachedCategorySchemas { get; private set; }
@jonny-jeahyunchoi  [delete CachedCategorySchemas](https://github.com/planetarium/NineChronicles/pull/4428/commits/2489df10dd69459a80305fcf62123bc80a25c37d) 이 커밋에서 _initailizedProductSchema로 옮겼습니다.

2024-03-15 08:24 UTC, jonny-jeahyunchoi commented on nekoyume/Assets/_Scripts/UI/Widget/MobileShop.cs
> +        public IReadOnlyList<CategorySchema> CachedCategorySchemas { get; private set; }
오 확인하였습니다~!

2024-03-15 08:25 UTC, merged