로컬레이어의 상태 초기화처리 수정
planetarium/NineChronicles pull request #5154
Opened 2024-06-21 08:47 UTC by ipdae

- 메일읽음처리시 블록높이따라 상태 초기화를 호출하도록 처리
- 퀘스트완료처리시 상태 초기화를 비활성화
- 축하팝업에서 상태 초기화를 비활성화
- resolve #5133 #5124

2024-06-21 08:54 UTC, eugene-doobu commented on nekoyume/Assets/_Scripts/UI/Widget/Popup/MailPopup.cs
> -                        LocalLayerModifier.RemoveNewAttachmentMail(avatarAddress, mail.id, true);
이거 resetState=false인 상태에서 코드 실행하는 경우 제작된 장비까지 인벤토리에 안담기는 상황은 없나요?

2024-06-21 09:00 UTC, eugene-doobu requested changes
reset state = false인 경우 인벤토리 갱신이 안되고 있습니다

2024-06-24 08:48 UTC, eugene-doobu commented
> reset state = false인 경우 인벤토리 갱신이 안되고 있습니다

19c4ed982f35e91ee8ab309f2f68edf04fe6f0e5 기준에서 UI갱신시 정상동작하는것으로 보여 self-requested를 통해 requested changes표시 지웠습니다

2024-06-25 01:13 UTC, sonohoshi approved these changes

2024-06-25 01:16 UTC, eugene-doobu approved these changes

2024-06-25 01:19 UTC, merged