Fix Item Craft & Enhancement item labels
planetarium/NineChronicles pull request #519
Opened 2021-07-19 07:47 UTC by plafina2

### Description

1. Fix Item Craft & Enhancement item labels

### How to test

1. check csv files
2. `common.csv` 하단에 삭제된 코드줄이 있는데 전에 스웬님께서 타국 언어는 영어로 넣어놓지 말라고 하셔서? 제가 가진 파일로 대체했으니 참고 부탁드립니다.

### Required Reviewers

@boscohyun @hskim881028 @Namyujeong

2021-07-19 07:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/planetarium/NineChronicles?pullRequest=519) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/planetarium/NineChronicles?pullRequest=519) before we can accept your contribution.<br/><hr/>**plafina2** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/planetarium/NineChronicles?pullRequest=519) it.</sub>

2021-07-19 16:11 UTC, Namyujeong commented
@plafina2 이거 번역은 제가 이어서 넣는 건가요?

2021-07-20 09:48 UTC, plafina2 commented
번역도 날 잡아서 제가 넣을게요. 일단 PR 쌓아놓는 중입니다.
컨플릭트는 지금 다시 보겠습니다.

2021-07-27 09:39 UTC, plafina2 commented
레이블 업데이트&문서반영 끝났습니다.
이제 리뷰 해주시면 되겠습니다.

2021-07-27 15:40 UTC, Namyujeong requested changes

2021-07-27 15:40 UTC, Namyujeong commented on nekoyume/Assets/StreamingAssets/Localization/common.csv
> +UI_COMBINATION_NOTIFY_FORMAT,"<size=12><color=#FFA78B>[Workshop Cat]</color></size>I've finished crafting {0}.","<size=12><color=#FFA78B>[대장장이 고양이]</color></size>{0} 제작을 완료하였네.","<size=12><color=#FFA
이쪽에 개행 무너져 있습니다. 이대로 올리면 다 한줄로 나올겁니다. combination-notify, combination-mail 쪽 모두 이전 csv 개행포맷을 맞춰주셔야 합니다.

2021-07-27 15:40 UTC, Namyujeong commented on nekoyume/Assets/StreamingAssets/Localization/common.csv
> +UI_COMBINATION_THIRD_RECIPE_TITLE,Mimir,미미르,Imir.,Imir.,ミミー,Mimir,Mimir,แมชชีน,Mimir.,Mimir,Mimir,Mimir.,Mimir,Мимир,មមមី,Mimir.,咪咪,Mimir
Mimisbrunnr의 약자를 Mimir 라고 쓰는 것이 통상적인 표현인가요?

2021-07-27 15:40 UTC, Namyujeong commented on nekoyume/Assets/StreamingAssets/Localization/common.csv
> +UI_RECIPE_EMPTY_STATE,Please select a recipe.,레시피를 선택해주세요.,Por favor, selecione uma receita.,Por favor, selecione uma receita.,レシピを選択してください。,Bitte wählen Sie ein Rezept aus.,Por favor, seleccione una
이전 문서에서도 피드백 드렸습니다만, 레시피를 선택하는게 아니라 제작할 아이템을 선택하라고 해야 하지 않을까요?
아이템에 3개의 레시피가 딸린 것이고, 유저가 아이템을 레시피로 인지하지는 않을 것 같습니다.

2021-07-27 15:40 UTC, Namyujeong commented on nekoyume/Assets/StreamingAssets/Localization/common.csv
> +UI_ACCELERATE,Accelerate :,빠른 제작 :,acelerar:,acelerar:,加速：,Beschleunigen :,acelerar:,เร่งความเร็ว :,Przyspieszenie:,pagreitinti:,Versnellen :,mempercepat:,Accélérer :,Ускорение:,បង្កើនល្បឿន:,تیز:,加速
이 레이블의 콜론과 공백은 무엇인가요?

2021-07-27 15:40 UTC, Namyujeong commented on nekoyume/Assets/StreamingAssets/Localization/elemental_type.csv
> +ELEMENTAL_TYPE_NORMAL,Normal,무,Normal,,ノーマル,Normal,,ธรรมดา,Normalny,,Normaal,normal,Normal,Нормально,ធម្មតា,,普通,
한글레이블이 공식적으로 노출되지는 않을거지만, '무'는 좀 어색하지 않나요? 근데 이것만 무속성이라고 되어있으면 그건 그것대로 이상한가.. 의견이 궁금합니다.

2021-07-27 15:40 UTC, Namyujeong commented on nekoyume/Assets/StreamingAssets/Localization/enum_type.csv
> +ITEM_SUB_TYPE_GRADE_1,Normal,노멀,Normal,Normal,正常,Normal,Normal,ปกติ,Normalna,Normalus,normaal,Normal,Normal,Обычный,ធម្មតា,عمومی,普通的,Normál
이쪽에는 번역이 들어가있는데, common.csv 최하단의 `UI_ITEM_GRADE_n` 이쪽에는 왜 일괄 영문으로 넣어놓으셨나요?

2021-07-28 06:22 UTC, plafina2 commented on nekoyume/Assets/StreamingAssets/Localization/common.csv
> +UI_COMBINATION_NOTIFY_FORMAT,"<size=12><color=#FFA78B>[Workshop Cat]</color></size>I've finished crafting {0}.","<size=12><color=#FFA78B>[대장장이 고양이]</color></size>{0} 제작을 완료하였네.","<size=12><color=#FFA
해당 내용 수정하였으니 리뷰 부탁드립니다.

2021-07-28 06:22 UTC, plafina2 commented on nekoyume/Assets/StreamingAssets/Localization/common.csv
> +UI_COMBINATION_THIRD_RECIPE_TITLE,Mimir,미미르,Imir.,Imir.,ミミー,Mimir,Mimir,แมชชีน,Mimir.,Mimir,Mimir,Mimir.,Mimir,Мимир,មមមី,Mimir.,咪咪,Mimir
미미르의 샘이 Mimisbrunnr
거인 미미르를 Mimir
라고 하는데 레시피 자체는 거인의 레시피라고 생각하는 게 맞을 듯해서 Mimir 사용했습니다.
(UI 문제까지 고려하였음)

2021-07-28 06:23 UTC, plafina2 commented on nekoyume/Assets/StreamingAssets/Localization/common.csv
> +UI_RECIPE_EMPTY_STATE,Please select a recipe.,레시피를 선택해주세요.,Por favor, selecione uma receita.,Por favor, selecione uma receita.,レシピを選択してください。,Bitte wählen Sie ein Rezept aus.,Por favor, seleccione una
이 내용은 유정님께서 수정해주시길 부탁드립니다.

2021-07-28 06:23 UTC, plafina2 commented on nekoyume/Assets/StreamingAssets/Localization/common.csv
> +UI_ACCELERATE,Accelerate :,빠른 제작 :,acelerar:,acelerar:,加速：,Beschleunigen :,acelerar:,เร่งความเร็ว :,Przyspieszenie:,pagreitinti:,Versnellen :,mempercepat:,Accélérer :,Ускорение:,បង្កើនល្បឿន:,تیز:,加速
기존 UI에서 사용하던 `가속 :` 컨텍스트를 따랐습니다.

2021-07-28 06:23 UTC, plafina2 commented on nekoyume/Assets/StreamingAssets/Localization/elemental_type.csv
> +ELEMENTAL_TYPE_NORMAL,Normal,무,Normal,,ノーマル,Normal,,ธรรมดา,Normalny,,Normaal,normal,Normal,Нормально,ធម្មតា,,普通,
이거 이상하긴 해요 ㅋㅋㅋㅋㅋ 고민입니다 ㅜㅜ 뒤를 부탁합니다.

2021-07-28 06:24 UTC, plafina2 commented on nekoyume/Assets/StreamingAssets/Localization/enum_type.csv
> +ITEM_SUB_TYPE_GRADE_1,Normal,노멀,Normal,Normal,正常,Normal,Normal,ปกติ,Normalna,Normalus,normaal,Normal,Normal,Обычный,ធម្មតា,عمومی,普通的,Normál
그쪽 최하단의 일괄 영문은 승걸님께서 아이템 디스크립션 작업하시면서 직접 넣으신 거 같네요.

2021-07-28 13:36 UTC, Namyujeong commented on nekoyume/Assets/StreamingAssets/Localization/elemental_type.csv
> +ELEMENTAL_TYPE_NORMAL,Normal,무,Normal,,ノーマル,Normal,,ธรรมดา,Normalny,,Normaal,normal,Normal,Нормально,ធម្មតា,,普通,
'무' '무속성' 둘 다 쓰는데, 아이콘이 있는 경우에는 '무'를 더 많이 쓰는 경향으로 보여 '무' 유지하겠습니다.

2021-07-28 13:58 UTC, Namyujeong commented on nekoyume/Assets/StreamingAssets/Localization/common.csv
> +UI_ACCELERATE,Accelerate :,빠른 제작 :,acelerar:,acelerar:,加速：,Beschleunigen :,acelerar:,เร่งความเร็ว :,Przyspieszenie:,pagreitinti:,Versnellen :,mempercepat:,Accélérer :,Ускорение:,បង្កើនល្បឿន:,تیز:,加速
이쪽은 이대로 머지하고 콜론이 레이블에 있어야 할지 프리펩에 있어야 할지를 추후 보겠습니다.

2021-07-28 14:09 UTC, Namyujeong approved these changes

2021-07-28 14:24 UTC, merged