Update tutorial.
planetarium/NineChronicles pull request #558
Opened 2021-08-02 11:17 UTC by Unengine

### Description

SSIA

### How to test (in editor)

1. Set `isEditor` variable to `false` in `GameConfig.cs`.
2. Make genesis block.
3. Create new character and play tutorial.

### Required Reviewers
@planetarium/9c-dev @Namyujeong

2021-08-02 11:55 UTC, Namyujeong requested changes
The new tutorial flow successfully works!

1. but I think you might forget the issue.
https://app.asana.com/0/958521740385861/1200666243035455/f

2. Could you change the pointer type? (borderless, only pointer)
![image](https://user-images.githubusercontent.com/41294407/127857784-3b76ad11-6d28-4564-aeeb-0b6187317b66.png)

2021-08-03 02:09 UTC, Unengine commented
> The new tutorial flow successfully works!
> 
> 1. but I think you might forget the issue.
>    https://app.asana.com/0/958521740385861/1200666243035455/f
> 2. Could you change the pointer type? (borderless, only pointer)
>    ![image](https://user-images.githubusercontent.com/41294407/127857784-3b76ad11-6d28-4564-aeeb-0b6187317b66.png)

I thought this is a separate issue with [this](https://app.asana.com/0/958521740385861/1200521701229583).

2021-08-03 04:08 UTC, Namyujeong approved these changes

2021-08-03 04:42 UTC, hskim881028 approved these changes

2021-08-03 04:46 UTC, boscohyun approved these changes

2021-08-03 05:54 UTC, merged