create arena service client
planetarium/NineChronicles pull request #5665
Opened 2024-08-14 09:57 UTC by tyrosine1153

### Description

- resolve https://github.com/planetarium/NineChronicles/issues/5652

### How to test

1. clo.json에 "ArenaServiceHost" 인자를 추가합니다.
  형식: "{service host}/graghql"
2. 게임에 들어가 아레나 목록을 잘 불러오는지 확인합니다.

### Screenshot

2024-08-14 14:50 UTC, eugene-doobu approved these changes

2024-08-16 04:32 UTC, sonohoshi approved these changes

2024-08-16 07:36 UTC, ipdae approved these changes

2024-08-19 01:43 UTC, ipdae requested changes
런쳐쪽 작업하다 확인했는데, PlanetRegistry 작업이 누락되있는것같습니다.

2024-08-19 06:23 UTC, ipdae approved these changes

2024-08-19 06:53 UTC, merged