fix worldboss ticker serialization
planetarium/NineChronicles pull request #6128
Opened 2024-10-16 08:40 UTC by jonny-jeahyunchoi

월드보스 티커 직렬화 규칙 변경 대응

2024-10-17 05:30 UTC, ipdae requested changes

2024-10-17 05:30 UTC, ipdae commented on nekoyume/Assets/_Scripts/L10n/L10nManager.cs
> +        {
이거 Currencies에 이미 ticker 파싱을 도와주는 함수가 있습니다. 그걸 사용하는게 좋을것 같습니다.

2024-10-17 09:44 UTC, jonny-jeahyunchoi commented on nekoyume/Assets/_Scripts/L10n/L10nManager.cs
> +        {
https://github.com/planetarium/lib9c/blob/8f11988c4d8f65372425709a1dcbb9841f0ee108/Lib9c/Currencies.cs#L202
저게 ticker string 만 가지고 파싱해주는건 없어서 따로 만든부분이긴합니다~!

2024-10-17 10:29 UTC, ipdae commented on nekoyume/Assets/_Scripts/L10n/L10nManager.cs
> +        {
한번더 currency를 만들어야하는 상황이군요.. 일단 동작은 하는 상황이니 이해했습니다.

2024-10-17 10:29 UTC, ipdae approved these changes

2024-10-17 10:30 UTC, ipdae commented
@jonny-jeahyunchoi 어프루브는 했는데, 이렇게 파싱하면 아이템 몇개를 받았다는 식으로 표시가 되는건가요?

2024-10-18 01:46 UTC, jonny-jeahyunchoi commented
> @jonny-jeahyunchoi 어프루브는 했는데, 이렇게 파싱하면 아이템 몇개를 받았다는 식으로 표시가 되는건가요?

UI_RAID_SEASON_REWARD_MAIL_FORMAT 에 맞춰서 숫자먼저 아이템이름 뒤에 나오는 식으로 표시될 예정입니다
![image](https://github.com/user-attachments/assets/39fea603-7164-4f9c-937a-64b33630bdc4)
![image](https://github.com/user-attachments/assets/977a9bfc-13c3-4dde-b1b6-cabe2fd2a62b)

2024-10-18 06:50 UTC, merged