link escape key
planetarium/NineChronicles pull request #639
Opened 2021-08-13 12:32 UTC by hskim881028

### Description

- **Escape widget list**
![popup_1](https://user-images.githubusercontent.com/40553495/129357265-ac83c664-e380-4b5a-9d59-aab60b06997c.jpg)
![popup_2](https://user-images.githubusercontent.com/40553495/129357284-adba8d8a-466e-42c5-b26c-6f04b6cb5b46.jpg)

### Related Links

- [[기타] 팝업닫기는 esc로 매핑하고, 아무 팝업도 떠있지 않은 상태에서 esc를 누르면 종료팝업이 뜨도록](https://app.asana.com/0/958521740385861/1200757969884751/f)

### Required Reviewers

@Namyujeong , @planetarium/9c-dev 

### Screenshot

2021-08-13 17:10 UTC, Namyujeong requested changes
### ESC로 닫혀야함
- UI_Rank
- UI_CombinationResultBackup
- UI_EnhancementResultBackup

### Backspace로 매핑되어 있는데 ESC로 교체해야함
- UI_LoginPopup
- UI_Mail
- UI_Quest
- UI_Combinationslots

### 기타 오동작
- 아무 팝업 떠있지 않은 상태에서 Esc 눌렀을 때 종료팝업 뜨지 않음
- Sell에서 ItemCountanndPricePopup 띄운 뒤 Back버튼으로 메인으로 돌아가지 못함

2021-08-17 01:05 UTC, boscohyun approved these changes

2021-08-17 03:30 UTC, hskim881028 commented
> ### ESC로 닫혀야함
> * UI_Rank
> * UI_CombinationResultBackup
> * UI_EnhancementResultBackup
> 
> ### Backspace로 매핑되어 있는데 ESC로 교체해야함
> * UI_LoginPopup
> * UI_Mail
> * UI_Quest
> * UI_Combinationslots
> 
> ### 기타 오동작
> * 아무 팝업 떠있지 않은 상태에서 Esc 눌렀을 때 종료팝업 뜨지 않음
> * Sell에서 ItemCountanndPricePopup 띄운 뒤 Back버튼으로 메인으로 돌아가지 못함

수정했습니다 🙇🏻

2021-08-17 08:53 UTC, Namyujeong approved these changes
I will create a separate issue where item focus is not released after closing the item sale pop-up.

2021-08-17 08:53 UTC, merged