Design/balance v2
planetarium/NineChronicles pull request #742
Opened 2021-09-06 11:13 UTC by plafina2

### Description

1. Fix Craft V2 recipe production time & mimir equipment's power.

### How to test

1. First step.

### Related Links

### Required Reviewers

@Namyujeong 

### Screenshot

2021-09-06 12:02 UTC, Namyujeong requested changes
- 1성 불 미미르 벨트만 특별히 다른 1성 불 미미르 장비보다  블록 수가 1/6 정도인 이유가 있나요?
- 프리미엄 레시피보다 스킬 붙을 확률이 다시 줄어드는데, 칼의 경우 더 좋은 스킬이니까 그렇다 쳐도, 나머지 장비들은 붙는 스킬이 동일한데 스킬확률이 다시 줄어드니 이상해보입니다.
- 1성 불 미미르 장비들 중 일부는 브론즈 메달이 필요하고, 일부는 브론즈 메달이 필요 없는데 의도인가요? 다 있는게 좋을 것 같습니다.

2021-09-06 12:07 UTC, plafina2 commented
1. 불 미미르 벨트는 120 레벨에서 제작할 수 있는 장비라서 그렇습니다! (거기는 초반부라서 블록 요구치가 적습니다)
저희가 옛날에는 장비를 티어에 맞추기로 했었는데, 이번 개편에 따라 맞춰줘야 할 거 같아서 해당 내용을 테이블에 반영했습니다.

아울러 불 미미르 목걸이는 180 레벨 즈음에서 제작할 수 있는 장비입니다. 하지만 나머지 장비들이 200을 권장레벨로 하고 있기 때문에 그것과 크게 편차를 줄 필요는 없을 것 같아서 동일값을 넣었습니다.

2. 아울러 미미르 장비들의 재료인 브론즈 메달의 경우에도, 200레벨에 도달하여 제작하는 장비들에 들어가도록 되어있습니다.

3. 스킬 확률들은 말씀주신 게 맞는 것 같습니다. 다시 한 번 보겠습니다.

2021-09-06 12:20 UTC, Namyujeong commented
@plafina2

벨트만 3000블록 대이고 나머지만 요구블록수가 18000대이니까 일관성이 없어보여서요. 이번에 확률 조정 등을 진행했던 기조대로, 유저가 봤을 때에도 이게 어떤 스킴으로 디자인되어 있는 것인지  가늠이 어느정도 될 수 있도록 해야 할 것 같습니다.
 - 다른 레시피는 모두 동일계열일 경우 칼>아머>벨트>목걸이>반지 순으로 만들 수 있는데, 미미르일 경우에만 미미르 벨트를 맨 먼저 만들 수 있다는 것이 유저에게 전달이 잘 될 수 있을까요? 벨트 이후에는 아머인지 반지인지 칼인지 알 수 없습니다. 이전까지 그랬다 하더라도, 이번에 좀 더 인지가 될 수 있는 방향으로 정리되면 좋겠습니다.
 - 200장비부터 브론즈 메달이 재료로 들어가는 것이 의도이고, 벨트 외에는 200렙 장비인 것이 의도라면, 아머와 반지의 경우에는 왜 브론즈 메달이 안필요한가요? 이 부분이 설명되지 않습니다. 
 - 요구블록수 역시 벨트를 제외하고 모두 거의 동일한 와중에 반지만 또 살짝 다릅니다. 이 부분도 어떤 스킴으로 레시피가 구성되어 있는지 인지하기가 어려운 부분 중 하나입니다.

몇 안되는 오픈된 미미르 레시피지만, 테이블 패치를 할 수 있는 기회이니 이런 부분들을 이번에 개선해봅시다.

2021-09-07 06:36 UTC, plafina2 commented
1. 미미르 장비의 블록 요구 시간을 동일하게 3천으로 맞췄습니다. 반지도 포함입니다.
2. 200 이전에 제작할 수 있는 벨트와 목걸이를 제외하고 모든 장비에서 엠블렘 15개를 요구합니다.
3. 미미르 장비들의 대성공 확률을 프리미엄 레시피보다 소폭 높게 잡았습니다. 단, 종결장비인 반지는 제외입니다.
4. 인지성 측면은 현재 라이브된 설계의 부족함을 실감하나, 이미 라이브된 데이터를 고치기에 조심스럽습니다. 다음 미미르부터는 인지측면을 더 높게 고려하도록 하겠습니다.

![image](https://user-images.githubusercontent.com/60082897/132295629-fd8fa6ad-673e-46f8-b283-e8cefe689f14.png)
![image](https://user-images.githubusercontent.com/60082897/132295639-121dba05-7930-45c8-9ecb-d24d4608cef7.png)
![image](https://user-images.githubusercontent.com/60082897/132295650-f79dc882-5ba3-48d2-9170-54e625b3c7f0.png)
![image](https://user-images.githubusercontent.com/60082897/132295656-093b4e6c-21fa-4d96-8ed9-2ad0396132be.png)
![image](https://user-images.githubusercontent.com/60082897/132295662-7a4b3222-2a2e-44ce-9c8c-cddda31f7834.png)

2021-09-07 07:35 UTC, plafina2 commented
1. 블록 개수를 풀리는 순서대로 조정했습니다. 각각 풀리는 레벨을 고려하여 벨트(100~120) 목걸이(160~180) 천옷(200) 롱소드(200) 반지(200) 순으로 증가합니다.
2. 재료 수량을 조정했습니다. 엠블렘의 경우 획득순서가 늦을수록 많은 수량을 요구하도록 했고, 아울러 이번 v2 기조인 재료 요구치 2~3배로 늘리는 조정을 가했습니다. 아울러 표적파밍에 대한 부분도 넣고 싶기는 한데 이건 작업시간이 좀 걸려서 이번에 하지 않습니다. (만약 이걸 했다면 재료 요구치도 더 올렸을 건데, 그걸 감안해서 2~3배로 그쳤습니다)

이하 스크린샷 정렬은 획득 순서대로 정렬했습니다. 벨트 목걸이 천옷 롱소드 반지 순

![image](https://user-images.githubusercontent.com/60082897/132303638-079a177d-4b08-4792-b85f-9764d8bbf104.png)
![image](https://user-images.githubusercontent.com/60082897/132303652-8864e117-78e0-4d7d-ac18-33ff0aaff8ab.png)
![image](https://user-images.githubusercontent.com/60082897/132303673-2cae204c-45fb-4da7-9843-4c499df6f78e.png)
![image](https://user-images.githubusercontent.com/60082897/132303697-c4f89562-917d-4424-a7b1-b36e63c0466a.png)
![image](https://user-images.githubusercontent.com/60082897/132303709-81791045-0ba8-482a-99f2-0ded8b308d69.png)

2021-09-07 07:57 UTC, Namyujeong approved these changes

2021-09-07 07:57 UTC, merged