Bug fix/result popup vfx
planetarium/NineChronicles pull request #743
Opened 2021-09-06 11:20 UTC by boscohyun

### Related Links

1. [[제작강화결과] 뒤에 메일 창이 떠 있을 때 아이템 vfx가 안 보이는 문제](https://app.asana.com/0/958521740385861/1200887083113945/f)

2021-09-08 09:56 UTC, Unengine approved these changes

2021-09-08 13:44 UTC, Namyujeong requested changes
Is it normal? Some strange points are showing.

https://user-images.githubusercontent.com/41294407/132520905-e64a2bd6-86c8-4784-a23a-f75fc8a17aff.mov


![image](https://user-images.githubusercontent.com/41294407/132520756-84de7524-1616-4cad-9465-8474f2ef190b.png)

2021-09-08 16:01 UTC, hskim881028 approved these changes

2021-09-09 09:44 UTC, Namyujeong approved these changes

2021-09-09 09:50 UTC, merged